name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: 📦 Publish to RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Build & Push Gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem
          printf -- "---\n:rubygems_api_key: %s\n" "${RUBYGEMS_API_KEY}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem build smallpict.gemspec
          gem push smallpict-*.gem
